# Generated by Django 5.0.6 on 2024-05-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippetApp', '0002_rename_timestamp_snippet_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='tags',
            field=models.ManyToManyField(blank=True, to='snippetApp.tag'),
        ),
    ]
